import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFile} from 'node:fs/promises'
import {PGlite} from '@electric-sql/pglite'
import {grantsPaidAccess,paidAccessUntil,stripeObjectId,hasCurrentPaidAccess} from '../lib/subscriptionPolicy'
import {subscriptionEventTarget} from '../lib/subscriptionEvent'
import type Stripe from 'stripe'

test('subscription display access expires and fails closed for unknown dates',()=>{
  assert.equal(hasCurrentPaidAccess({status:'active',paid_until:new Date(2000).toISOString()},1000),true)
  for(const paid_until of [null,'invalid',new Date(1000).toISOString()]) assert.equal(hasCurrentPaidAccess({status:'active',paid_until},1000),false)
  assert.equal(hasCurrentPaidAccess({status:'inactive',paid_until:new Date(2000).toISOString()},1000),false)
  assert.equal(hasCurrentPaidAccess(null,1000),false)
})

test('verified event routing covers renewals and never trusts billing email for ownership',()=>{
  const event=(type:string,object:unknown)=>({type,data:{object}} as Stripe.Event)
  for(const type of ['checkout.session.completed','checkout.session.async_payment_succeeded']) {
    assert.deepEqual(subscriptionEventTarget(event(type,{mode:'subscription',subscription:'sub_1',customer_email:'untrusted@example.test',metadata:{user_email:'owner@example.test'}})),{id:'sub_1',email:'owner@example.test'})
    assert.deepEqual(subscriptionEventTarget(event(type,{mode:'subscription',subscription:{id:'sub_1'},customer_email:'untrusted@example.test'})),{id:'sub_1',email:undefined})
    assert.equal(subscriptionEventTarget(event(type,{mode:'payment',subscription:'sub_1'})),null)
  }
  for(const type of ['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted','customer.subscription.paused','customer.subscription.resumed']) assert.deepEqual(subscriptionEventTarget(event(type,{id:'sub_1'})),{id:'sub_1'})
  for(const type of ['invoice.paid','invoice.payment_failed','invoice.payment_action_required','invoice.finalization_failed']) {
    assert.deepEqual(subscriptionEventTarget(event(type,{parent:{subscription_details:{subscription:'sub_1'}}})),{id:'sub_1'})
    assert.equal(subscriptionEventTarget(event(type,{parent:null})),null)
  }
  assert.equal(subscriptionEventTarget(event('customer.created',{id:'cus_1'})),null)
})

test('paid access requires active status, correct price, quantity and no payment pause',()=>{
  const active={status:'active',pause_collection:null,latest_invoice:{status:'paid'},items:{data:[{price:{id:'price_folup'},quantity:1,current_period_end:2000}]}} as Parameters<typeof paidAccessUntil>[0]
  assert.equal(grantsPaidAccess(active,'price_folup'),true)
  for(const status of ['past_due','canceled','trialing','incomplete','incomplete_expired','unpaid','paused'] as const) assert.equal(grantsPaidAccess({...active,status},'price_folup'),false)
  assert.equal(grantsPaidAccess(active,'price_other'),false)
  assert.equal(grantsPaidAccess(active,''),false)
  assert.equal(grantsPaidAccess({...active,pause_collection:{behavior:'void',resumes_at:null}},'price_folup'),false)
  assert.equal(stripeObjectId({id:'sub_test'}),'sub_test');assert.equal(stripeObjectId(null),null)
  assert.equal(paidAccessUntil(active,'price_folup',1000_000),new Date(2000_000).toISOString())
  assert.equal(paidAccessUntil(active,'price_folup',2000_000),null)
  for(const latest_invoice of [null,'in_unexpanded',...['draft','open','void','uncollectible'].map(status=>({status}))]) {
    assert.equal(paidAccessUntil({...active,latest_invoice} as Parameters<typeof paidAccessUntil>[0],'price_folup',1000_000),null,'Active alone is not evidence of a paid invoice')
  }
})

test('subscription sync is idempotent, ordered and isolated from public roles',async()=>{
  const db=new PGlite()
  try {
    await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;
      CREATE TABLE subscriptions(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id text UNIQUE NOT NULL,stripe_customer_id text,stripe_subscription_id text,status text);`)
    await db.exec(await readFile('supabase/migrations/20260911000100_ai_usage_limits.sql','utf8'))
    await db.exec(await readFile('supabase/migrations/20260911000300_subscription_sync.sql','utf8'))
    const sync=async(id:string,status:string,created:number,checked:number)=>db.query('SELECT sync_subscription_status($1,$2,$3,$4,$5,$6,$7)', ['test@example.test','cus_test',id,status,created,new Date(checked*1000).toISOString(),status==='active'?new Date((checked+86400)*1000).toISOString():null])
    const row=async()=>(await db.query<{status:string;stripe_subscription_id:string}>('SELECT status,stripe_subscription_id FROM subscriptions')).rows[0]
    await sync('sub_1','active',100,1000);await sync('sub_1','active',100,1000)
    assert.equal((await db.query('SELECT * FROM subscriptions')).rows.length,1)
    await sync('sub_1','inactive',100,1100);await sync('sub_1','active',100,1050)
    assert.equal((await row()).status,'inactive')
    await sync('sub_1','active',100,1200)
    await sync('sub_2','inactive',200,1300)
    assert.equal((await row()).status,'active','A failed duplicate checkout must not revoke existing paid access')
    await sync('sub_2','active',200,1400)
    await sync('sub_1','inactive',100,1500)
    assert.deepEqual(await row(),{status:'active',stripe_subscription_id:'sub_2'})
    for(const role of ['anon','authenticated']) {
      await db.exec(`SET ROLE ${role}`)
      await assert.rejects(()=>sync('sub_attack','active',300,2000),/permission denied/)
      await db.exec('RESET ROLE')
    }
    await db.exec('SET ROLE service_role')
    await sync('sub_2','inactive',200,1600)
    await db.exec('RESET ROLE')
    assert.equal((await row()).status,'inactive')
    await db.exec(`INSERT INTO ai_usage(user_id,structures) VALUES ('test@example.test',10)`)
    const reserve=async()=>(await db.query<{reserve_ai_usage:string}>("SELECT reserve_ai_usage('test@example.test','structure')")).rows[0].reserve_ai_usage
    assert.equal(await reserve(),'quota_exceeded')
    await db.exec("UPDATE subscriptions SET status='active',paid_until=now()+interval '1 day'")
    assert.equal(await reserve(),'allowed')
    await db.exec("UPDATE subscriptions SET paid_until=now()-interval '1 second'")
    assert.equal(await reserve(),'quota_exceeded','Missed cancellation/renewal events cannot grant unlimited AI forever')
    await db.exec('UPDATE subscriptions SET paid_until=NULL')
    assert.equal(await reserve(),'quota_exceeded','Unreconciled legacy rows fail closed')
  } finally {await db.close()}
})
