import { FolupLogo } from '../../components/folup-branding'
import AnalyticsPreference from './AnalyticsPreference'

export default function PublicLanding({onSignIn}:{onSignIn:()=>void}) {
  return <div className="marketing">
    <a className="mk-skip" href="#main-content">Skip to content</a>
    <header className="mk-nav"><FolupLogo src="/folup_logo.png" width={3077} height={1200} imgClassName="h-9 w-auto" /><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="/try">Explore the demo</a><button onClick={onSignIn} type="button" className="mk-text-button">Sign in</button></nav></header>
    <main id="main-content">
      <section className="mk-hero">
        <div className="mk-hero-copy"><p className="mk-eyebrow"><span className="mk-dot" /> FOR SALESPEOPLE OUT IN THE FIELD</p><h1>Leave the visit.<br /><span>Keep the<br className="mk-desktop-break" /> momentum.</span></h1><p className="mk-lede">Say what happened. Leave with clear follow-ups, a CRM note and a smarter next move.</p><div className="mk-hero-ctas"><a href="/try" className="mk-primary">Try Your Own Visit</a><button onClick={onSignIn} type="button" className="mk-secondary">Start free trial</button></div><p className="mk-fine">No account needed to try. 14-day trial, no card.</p><div className="mk-compat"><span>English + Spanish</span><span>Phone + desktop</span><span>Your existing CRM</span></div></div>
        <figure className="mk-hero-product" aria-label="Illustrative example of a field note and follow-ups"><figcaption><span>FROM THE FIELD</span><span>Illustrative example</span></figcaption><div className="mk-paper"><div className="mk-paper-top"><span className="mk-note-icon" aria-hidden="true">≋</span><span>After the Northstar visit</span><span className="mk-fine">Your recap</span></div><blockquote>“She likes the A4, but <em>her engineer needs to review it.</em> Send the spec sheet tomorrow — no prices. They’ll talk Thursday.”</blockquote></div><div className="mk-thread" aria-hidden="true">↓</div><div className="mk-preview-result"><p className="mk-contact">Maya — Northstar</p><div className="mk-preview-agreed"><span className="mk-outline-icon" aria-hidden="true">✓</span><div><strong>Send the spec sheet</strong><p>No prices. Tomorrow · 9:00 AM</p><small>Proposed time</small></div></div><div className="mk-smart"><div className="mk-smart-label">SMART NEXT STEP <span className="mk-pill">Proposed</span></div><h2>Unblock the technical review.</h2><p>Ask Maya what her engineer needs to approve a trial, after their Thursday conversation.</p><div className="mk-when">Friday · 3:00 PM <span>· proposed schedule</span></div></div><p className="mk-preview-footer">CRM note ready to copy</p></div><p className="mk-fine mk-product-caption">Your commitments, intact. Your next move, considered.</p></figure>
      </section>
      <section className="mk-how" id="how-it-works"><div className="mk-section-heading"><p className="mk-eyebrow">LESS ADMIN. MORE FOLLOW-THROUGH.</p><h2>Less to type. More to act on.</h2></div><ol>{[['01','Say it while it’s fresh.','A voice note after the visit. Names, promises, questions — in your own words.'],['02','Find the next move.','Keep your commitments clear. Smart Next Step suggests a way past the sales blocker—not an invented agreement.'],['03','Make the next move.','You choose what goes into your calendar. Copy a clean note into your CRM.']].map(([n,title,body])=><li key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
      <section className="mk-faq"><div><p className="mk-eyebrow">A FEW GOOD QUESTIONS</p><h2>Your next visit,<br />with less admin.</h2><p>See the whole flow before you sign up.</p><a className="mk-primary mk-faq-cta" href="/try">Try Your Own Visit</a></div><div>{[
        ['Does Folup replace my CRM?','No. It prepares a clear visit note you can copy into your existing CRM. It does not automatically sync with Salesforce or HubSpot.'],
        ['How does Google Calendar work?','Connect Google Calendar, review the date and time, then add the follow-ups you choose. Folup does not send invitations to your contacts.'],
        ['What is included in the free trial?','14 days free, with up to 100 notes and Smart Next Step included. No credit card. The trial starts with your first successfully processed real note. Pro is $19/month.'],
        ['What if the AI gets something wrong?','Review the people, actions and timing before adding them to your calendar. Correct by voice when needed. A recommendation is not an agreed meeting.'],
      ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
    </main><footer className="mk-footer"><p><strong>folup</strong> Less admin. More follow-through.</p><AnalyticsPreference /><a href="/try">Explore the demo</a></footer>
  </div>
}
