import {DateTime} from 'luxon'
import {VISIT_PROMPT,VISIT_SCHEMA,parseVisitExtraction,type VisitAction,type VisitExtraction} from './visitExtraction'

// Separate wire fields prevent advice being interpreted as a reported commitment.
export const SALES_SCHEMA = {...VISIT_SCHEMA,
  properties:{...VISIT_SCHEMA.properties,recommendations:{type:'array',maxItems:1,items:{type:'object',additionalProperties:false,
    required:['action','rationale','timingReason'],properties:{action:VISIT_SCHEMA.properties.actions.items,
      rationale:{type:'string'},timingReason:{type:'string'}}}}},
  required:[...VISIT_SCHEMA.required,'recommendations'],
}

export const SALES_PROMPT = `${VISIT_PROMPT}
SOURCE AND CERTAINTY FIDELITY
For every claim, preserve who supplied it, its certainty, and its status (possible, intended, pending, completed, approved or rejected) in summary, insights and action descriptions. Never increase certainty while shortening text. First-person hesitation such as 'creo', 'no lo apunté bien', 'I think' or 'I may have misheard' belongs to the dictating salesperson unless explicitly quoted as someone else's words. It does NOT mean the customer is unsure, estimated, failed to confirm, or changed their mind. If the source of uncertainty is unclear, qualify the datum neutrally instead of assigning doubt to a person. 'Tienen ochenta acres, ochenta y cinco creo, no lo apunté bien' => 'Superficie aproximada de 80–85 acres', NOT 'Roberto calcula/no está seguro/no confirmó la cifra'. Conversely, 'Roberto dijo que él no sabe si son 80 o 85 acres' must preserve Roberto as the source of that uncertainty. Preserve exact confirmed figures when the source states them; do not hedge every fact indiscriminately.
Keep uncertain quantities attached to the right person, product and unit; never blend two customers' quantities into one range. '80 acres with Roberto, 85 with Laura' is not 80–85 acres for either. Apply negation and conditions to their own clause: possible iron deficiency is not a diagnosis; interest in a trial is not approval; a planned PCA/lab consultation is not completed or an already reported problem. Distinguish the rep's hypothesis from the customer's observation. A narrator's repair changes the recorded meaning, not the customer's business history. Do not write a completed event in CRM or Calendar merely because it would make a recommendation easier to explain.
DICTATION REPAIR IS NOT A BUSINESS EVENT
Apply the speaker's final corrected meaning without inventing a history for the discarded words. 'Send a quote, no sorry, only the technical sheet without prices' means a sheet-only send, NOT a canceled quote, withdrawn offer, rejected purchase or changed customer decision. 'La prueba fue mal, no, me expliqué mal: aún no la han evaluado' means the trial is not yet evaluated, NOT that the customer clarified its performance or that it performed well/badly. Do not attribute the narrator's repair to the customer. In summary, insights and actions retain the corrected meaning, not a story about the repair.
Conversely, preserve a real cancellation, rejection or withdrawal when the note explicitly reports that business event: 'The customer canceled yesterday's quote request; send the sheet instead' DOES establish a canceled request. Do not erase real events just because they also include replacement instructions. Resolve the scope per person and item; one correction never cancels another person's task.
Preserve the source of restrictions: 'Do not contact Nadia again' establishes a no-contact instruction, NOT that Nadia requested it. Write 'No further contact with Nadia' unless the note explicitly attributes the request to her. An unattributed instruction must not become customer speech or a customer decision.
COMPLETE CRM CONTEXT
Preserve stated future rep travel/presence with its customer or location and time window even when it is not an agreed customer appointment. 'I will be at Elena's farm next week' must survive as planned future presence: in summary if it is background availability, or in actions if the source clearly commits to a visit. Never omit it from BOTH. 'I will be in Santa Maria next week' is travel context, not a booked meeting or a past visit. Do not invent its purpose, attendees or exact day. A Smart Next Step to coordinate does not replace an existing planned visit. If a visit is already an explicit action, do not duplicate it in summary. Before returning, check that all stated future presence is represented and remains future, including in multi-customer notes.
Write summary as one short paragraph per customer when the note covers separate customer conversations, separated by a blank line. Begin each paragraph with its customer's name/organization. Do not split people from the same meeting unnecessarily. Keep information with its actual owner; never regroup using name guesses. Preserve important facts, restrictions and commitments. Omit transcription bookkeeping: '80–85 acres approximately' preserves the narrator's uncertainty without 'not written down correctly'. Omit statements about a mentioned competitor not attending unless attendance itself has a material commercial consequence; retain their competitor role and any actual offer or objection. Do not delete real cancellations or who expressed doubt.
summary is the complete, concise factual CRM narrative, written once. Every important fact used in insights MUST also be covered in summary with the same owner, quantities, uncertainty, negation and conditions. Insights are shorter screen highlights, NOT extra facts to append to CRM. The application exports summary alone, then explicit actions and separately labelled recommendations. Keep outstanding rep actions in actions, not repeated in summary; preserve customer-owned commitments and restrictions as context. Avoid repeating any fact in summary and do not narrate the act of dictation or correction.
Do not infer an encounter, communication channel or physical meeting location from the app's post-visit framing. 'Eva at Hillcrest wants to consider a trial' states an affiliation and interest, NOT 'Met with Eva at Hillcrest'. Start with substantive facts, e.g. 'Eva wants to consider a trial only after permit approval.' Write 'Met/Visited/Reunión/Visita' only when the source explicitly describes that encounter. A company affiliation is not a visited physical location. Keep location empty unless the source explicitly establishes where a visit took place. A future consultation, possible laboratory issue or question must never become a reported incident.
SALES RECOMMENDATION CONTRACT
All rules above govern factual extraction and explicit commitments in actions. Independently, recommendations may contain zero or ONE useful proposed rep action. Never put inferred actions in actions, summary, insights or header identities. Advice is not an agreement or a past fact. Preserve every explicit commitment.
Use only this note and its reference date. Unknown stage, authority, urgency or buying intent remain unknown. Never invent history, stakeholder access, product claims or contact permission. No duplicate actions or multi-step campaigns. Apply this decision order separately to each customer's situation; output at most one recommendation overall:
1. Preserve outstanding explicit rep commitments first. An AI recommendation must not replace, weaken, reschedule or discard them. Customer-owned commitments remain context, not rep tasks.
2. Identify the nearest unresolved prerequisite supported by the note: missing information, technical validation, permission, credit, commercial terms, timing, or a decision. Address that prerequisite, not a later sale milestone. A price objection does not authorize a discount; credit trouble does not authorize shipment; interest does not authorize a trial. Do not invent a missing document, technical answer or buying stage.
3. Check whether an existing rep commitment already addresses that prerequisite. If yes, add no generic check-in, reminder to perform that commitment, or speculative downstream task for that same purpose. Already-sent information is not a new send. A different customer's unresolved need may still justify the one recommendation.
4. Respect the next actor and contact boundaries. When a customer must speak to their advisor or approver, work through the known customer, not a direct call to an unintroduced stakeholder. Consider whether proposing coordination of a technical review through that customer would address the prerequisite better than a status check, but only when the note supports a concrete opportunity for it. If permission, trial results or approval are pending, do not schedule dependent execution or assume success. Keep the condition explicit and the instruction short.
5. Distinguish permanent requests not to contact from temporary pauses. Permanent opt-out, rejected opportunity, completed matter, or polite interest alone ("maybe someday") => no recommendation. An unresolved concrete objective plus "not until Monday" can justify a checkpoint on or after Monday, never before. A return date is availability, not proof that the prerequisite will be completed then. After repeated unanswered attempts allow breathing room; never create an immediate extra contact. "I will contact you; do not chase" means wait, not schedule an unsolicited chase. If the note gives no responsible basis for action or timing, return [].
BEST NEXT STEP SELECTION
Do not recommend the first reasonable follow-up. Determine what must happen next to materially advance the sale, within the customer's boundaries.
Before selecting, identify the supported commercial objective, nearest unresolved blocker, next actor and known decision makers/influencers. Distinguish actual buying signals from politeness; preserve objections, uncertainty and risks. Connect useful context across the note: rep travel, stakeholder availability, seasonal windows and customer deadlines. Do not assume a company, location, product variant or opportunity stage that was not established.
Internally compare up to three distinct, grounded candidate actions, plus waiting/no recommendation. Do not force three candidates or output the alternatives or a reasoning transcript. First discard candidates that violate restrictions, bypass a stakeholder, duplicate an explicit commitment, rely on an invented fact or assume a prerequisite has succeeded. Among eligible candidates prefer the one that most directly advances the supported blocker and takes advantage of a real timing window. Use lower customer burden as a tie-breaker, not as a reason to choose a generic status check over a supported coordination opportunity. Do not rank by invented deal value, urgency or numerical closing probability. Return no recommendation when no eligible additional action adds value.
For a coordination proposal, action.date is when the rep should CONTACT the known customer to coordinate, with lead time before the target meeting/window where feasible. It is NOT the date of an already-booked meeting. A habitual Wednesday visit is not confirmed availability; frame it as a proposed option, not a scheduled appointment. Explicit pauses override travel convenience and seasonal urgency. If windows conflict, do not claim they coincide. Never invent an exact flowering date from an approximate interval. A proposed trial is not an approved trial.
rationale briefly states the specific blocker the selected action addresses; timingReason connects the relevant supported window or waiting period to the suggested action date. Keep the selected instruction concise and executable, with a short purpose when useful, not a sales-analysis essay in CRM. Preserve the existing output schema: one recommendation at most, with all explicit commitments separately retained.
recommendation.action uses the same fields, but description is a proposed instruction and evidence quotes the exact passage establishing the unresolved need, NOT a supposed commitment. contact must be a confirmed contact in contacts; company must be in companies or empty. If identity or recipient/company relationship is unclear, omit the recommendation. subject names the proposed topic without inventing a deliverable. rationale briefly explains the practical purpose grounded in the note. timingReason briefly explains timing. Both use the note language.
For recommendations only, choose a concrete YYYY-MM-DD date based on context and the local reference date. It is always suggested, never agreed. Explicit expectations and waiting periods override cadence defaults. Leave time empty unless a relevant clock time was stated. Do not choose elapsed slots. When a prerequisite has an unknown completion date, propose a review/checkpoint to check its status, preserving the condition in description; never assume it happened or calculate a deadline from an imaginary event. Do not schedule the dependent execution itself. If insufficient context supports responsible advice, return recommendations=[].
Example: 'Mike liked Quantum but must discuss the trial with his PCA first' alone can support a check with Mike about that discussion, not a promised trial, invented technical-document send or direct PCA meeting. Additional context can change the best action: if the note also establishes a relevant rep trip, the PCA's habitual visit and a near flowering window, consider proposing coordination through Mike ahead of that window instead of a generic check. Do not turn habitual availability into a confirmed meeting or expand 'Quantum' to 'Quantum Flower' without source support. 'Do not contact me again' supports no recommendation. Never leak advice into the factual CRM narrative.`

export function parseSalesDecision(raw:unknown,source:string,referenceAt:string,timezone:string):VisitExtraction {
  const factual=parseVisitExtraction(raw,source)
  factual.crmNarrativeVersion=1
  // The wire recommendation is adapted below; do not persist two mutable copies.
  delete (factual as VisitExtraction & {recommendations?:unknown}).recommendations
  factual.actions=factual.actions.map(a=>({...a,origin:'commitment',rationale:undefined,timingReason:undefined}))
  const recommendations=(raw as {recommendations?:unknown}).recommendations
  if(!Array.isArray(recommendations)||recommendations.length>1)throw Error('Invalid recommendations')
  const reference=DateTime.fromISO(referenceAt,{zone:timezone})
  if(!reference.isValid)throw Error('Invalid recommendation reference')
  for(const item of recommendations){
    if(!item || typeof item.rationale!=='string' || !item.rationale.trim() || typeof item.timingReason!=='string' || !item.timingReason.trim())throw Error('Invalid recommendation rationale')
    const action:VisitAction=parseVisitExtraction({...factual,actions:[item.action],questions:[]},source).actions[0]
    if(!action.date || DateTime.fromISO(action.date,{zone:timezone}).startOf('day')<reference.startOf('day'))throw Error('Invalid recommendation date')
    if(action.time && DateTime.fromISO(`${action.date}T${action.time}`,{zone:timezone})<=reference)throw Error('Elapsed recommendation time')
    if(!action.contact || !factual.contacts.includes(action.contact) || (action.company && !factual.companies.includes(action.company)))throw Error('Unconfirmed recommendation recipient')
    if(factual.questions.some(q=>q.field==='contact'||q.field==='company'))continue
    if(factual.actions.some(a=>a.contact===action.contact && a.company===action.company && a.description.trim().toLowerCase()===action.description.trim().toLowerCase()))continue
    factual.actions.push({...action,origin:'recommendation',rationale:item.rationale.trim(),timingReason:item.timingReason.trim()})
  }
  return factual
}
